// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCafXaXw7f8JWc7u2kvrUyFqJGqW8TV-Es',
    appId: '1:476762936282:web:5840cb6f11bf220aa3a6e3',
    messagingSenderId: '476762936282',
    projectId: 'aula-crud-836c0',
    authDomain: 'aula-crud-836c0.firebaseapp.com',
    databaseURL: 'https://aula-crud-836c0-default-rtdb.firebaseio.com',
    storageBucket: 'aula-crud-836c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxYZzVSAGCDZBdAOjTvNwIQlLllUDtnc',
    appId: '1:476762936282:android:22a4531d80d7cc9da3a6e3',
    messagingSenderId: '476762936282',
    projectId: 'aula-crud-836c0',
    databaseURL: 'https://aula-crud-836c0-default-rtdb.firebaseio.com',
    storageBucket: 'aula-crud-836c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD28c0dSX_8TlmOtqSimhvp8OUTMffmAlE',
    appId: '1:476762936282:ios:459e1d9f2028491fa3a6e3',
    messagingSenderId: '476762936282',
    projectId: 'aula-crud-836c0',
    databaseURL: 'https://aula-crud-836c0-default-rtdb.firebaseio.com',
    storageBucket: 'aula-crud-836c0.appspot.com',
    iosBundleId: 'com.example.buyBuddyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD28c0dSX_8TlmOtqSimhvp8OUTMffmAlE',
    appId: '1:476762936282:ios:d5193fef64585221a3a6e3',
    messagingSenderId: '476762936282',
    projectId: 'aula-crud-836c0',
    databaseURL: 'https://aula-crud-836c0-default-rtdb.firebaseio.com',
    storageBucket: 'aula-crud-836c0.appspot.com',
    iosBundleId: 'com.example.buyBuddyApp.RunnerTests',
  );
}
