// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnGkhTNv7kn0O4Rb84HyIONP5heqVwtq0',
    appId: '1:639504722297:web:5cad705e0dffcb54e027a8',
    messagingSenderId: '639504722297',
    projectId: 'buybuddy-833fc',
    authDomain: 'buybuddy-833fc.firebaseapp.com',
    databaseURL: 'https://buybuddy-833fc-default-rtdb.firebaseio.com',
    storageBucket: 'buybuddy-833fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoSkkg8O4REMPnE8_WVkvZORkFn22AC74',
    appId: '1:639504722297:android:443a6d7905694aaee027a8',
    messagingSenderId: '639504722297',
    projectId: 'buybuddy-833fc',
    databaseURL: 'https://buybuddy-833fc-default-rtdb.firebaseio.com',
    storageBucket: 'buybuddy-833fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH2g_0DqpsTciJhqQlLn1SCjs76CcXzT0',
    appId: '1:639504722297:ios:9e68c7b08c0c815de027a8',
    messagingSenderId: '639504722297',
    projectId: 'buybuddy-833fc',
    databaseURL: 'https://buybuddy-833fc-default-rtdb.firebaseio.com',
    storageBucket: 'buybuddy-833fc.appspot.com',
    iosBundleId: 'com.example.buyBuddyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH2g_0DqpsTciJhqQlLn1SCjs76CcXzT0',
    appId: '1:639504722297:ios:321b16ab01f102d0e027a8',
    messagingSenderId: '639504722297',
    projectId: 'buybuddy-833fc',
    databaseURL: 'https://buybuddy-833fc-default-rtdb.firebaseio.com',
    storageBucket: 'buybuddy-833fc.appspot.com',
    iosBundleId: 'com.example.buyBuddyApp.RunnerTests',
  );
}
